/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tradeGuardSol from "./TradeGuard.sol";
export type { tradeGuardSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { KYCRegistry } from "./KYCRegistry";
export type { MockKycSBT } from "./MockKycSBT";
export type { PriceOracle } from "./PriceOracle";
export type { RWAPool } from "./RWAPool";
export type { RWAToken } from "./RWAToken";
