/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface KYCRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLevel"
      | "institutionalLP"
      | "isRevoked"
      | "isVerified"
      | "kycSBTAddress"
      | "owner"
      | "paused"
      | "renounceOwnership"
      | "setInstitutionalLP"
      | "setPaused"
      | "transferOwnership"
      | "updateKYCSBT"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InstitutionalLPSet"
      | "KYCSBTUpdated"
      | "OwnershipTransferred"
      | "RegistryPaused"
      | "RegistryUnpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "institutionalLP",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRevoked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "kycSBTAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInstitutionalLP",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateKYCSBT",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getLevel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "institutionalLP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRevoked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kycSBTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInstitutionalLP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKYCSBT",
    data: BytesLike
  ): Result;
}

export namespace InstitutionalLPSetEvent {
  export type InputTuple = [lp: AddressLike, status: boolean];
  export type OutputTuple = [lp: string, status: boolean];
  export interface OutputObject {
    lp: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCSBTUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistryPausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistryUnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KYCRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): KYCRegistry;
  waitForDeployment(): Promise<this>;

  interface: KYCRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLevel: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  institutionalLP: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isRevoked: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isVerified: TypedContractMethod<
    [user: AddressLike, minLevel: BigNumberish],
    [boolean],
    "view"
  >;

  kycSBTAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setInstitutionalLP: TypedContractMethod<
    [lp: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateKYCSBT: TypedContractMethod<
    [newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLevel"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "institutionalLP"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRevoked"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<
    [user: AddressLike, minLevel: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "kycSBTAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInstitutionalLP"
  ): TypedContractMethod<
    [lp: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateKYCSBT"
  ): TypedContractMethod<[newAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "InstitutionalLPSet"
  ): TypedContractEvent<
    InstitutionalLPSetEvent.InputTuple,
    InstitutionalLPSetEvent.OutputTuple,
    InstitutionalLPSetEvent.OutputObject
  >;
  getEvent(
    key: "KYCSBTUpdated"
  ): TypedContractEvent<
    KYCSBTUpdatedEvent.InputTuple,
    KYCSBTUpdatedEvent.OutputTuple,
    KYCSBTUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RegistryPaused"
  ): TypedContractEvent<
    RegistryPausedEvent.InputTuple,
    RegistryPausedEvent.OutputTuple,
    RegistryPausedEvent.OutputObject
  >;
  getEvent(
    key: "RegistryUnpaused"
  ): TypedContractEvent<
    RegistryUnpausedEvent.InputTuple,
    RegistryUnpausedEvent.OutputTuple,
    RegistryUnpausedEvent.OutputObject
  >;

  filters: {
    "InstitutionalLPSet(address,bool)": TypedContractEvent<
      InstitutionalLPSetEvent.InputTuple,
      InstitutionalLPSetEvent.OutputTuple,
      InstitutionalLPSetEvent.OutputObject
    >;
    InstitutionalLPSet: TypedContractEvent<
      InstitutionalLPSetEvent.InputTuple,
      InstitutionalLPSetEvent.OutputTuple,
      InstitutionalLPSetEvent.OutputObject
    >;

    "KYCSBTUpdated(address,address)": TypedContractEvent<
      KYCSBTUpdatedEvent.InputTuple,
      KYCSBTUpdatedEvent.OutputTuple,
      KYCSBTUpdatedEvent.OutputObject
    >;
    KYCSBTUpdated: TypedContractEvent<
      KYCSBTUpdatedEvent.InputTuple,
      KYCSBTUpdatedEvent.OutputTuple,
      KYCSBTUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RegistryPaused(address)": TypedContractEvent<
      RegistryPausedEvent.InputTuple,
      RegistryPausedEvent.OutputTuple,
      RegistryPausedEvent.OutputObject
    >;
    RegistryPaused: TypedContractEvent<
      RegistryPausedEvent.InputTuple,
      RegistryPausedEvent.OutputTuple,
      RegistryPausedEvent.OutputObject
    >;

    "RegistryUnpaused(address)": TypedContractEvent<
      RegistryUnpausedEvent.InputTuple,
      RegistryUnpausedEvent.OutputTuple,
      RegistryUnpausedEvent.OutputObject
    >;
    RegistryUnpaused: TypedContractEvent<
      RegistryUnpausedEvent.InputTuple,
      RegistryUnpausedEvent.OutputTuple,
      RegistryUnpausedEvent.OutputObject
    >;
  };
}
