/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockKycSBTInterface extends Interface {
  getFunction(
    nameOrSignature: "getKycInfo" | "isHuman" | "levels" | "setKyc" | "statuses"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getKycInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isHuman",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "levels", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setKyc",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "statuses",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getKycInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isHuman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "levels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setKyc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "statuses", data: BytesLike): Result;
}

export interface MockKycSBT extends BaseContract {
  connect(runner?: ContractRunner | null): MockKycSBT;
  waitForDeployment(): Promise<this>;

  interface: MockKycSBTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getKycInfo: TypedContractMethod<
    [account: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        ensName: string;
        level: bigint;
        status: bigint;
        createTime: bigint;
      }
    ],
    "view"
  >;

  isHuman: TypedContractMethod<
    [account: AddressLike],
    [[boolean, bigint]],
    "view"
  >;

  levels: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setKyc: TypedContractMethod<
    [account: AddressLike, level: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  statuses: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getKycInfo"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        ensName: string;
        level: bigint;
        status: bigint;
        createTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isHuman"
  ): TypedContractMethod<[account: AddressLike], [[boolean, bigint]], "view">;
  getFunction(
    nameOrSignature: "levels"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setKyc"
  ): TypedContractMethod<
    [account: AddressLike, level: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "statuses"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  filters: {};
}
