/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DEVIATION"
      | "MAX_STALENESS"
      | "circuitBreaker"
      | "getPrice"
      | "keeper"
      | "owner"
      | "priceStore"
      | "pushRWAPrice"
      | "registerFeed"
      | "renounceOwnership"
      | "resetCircuitBreaker"
      | "setKeeper"
      | "setMaxDeviation"
      | "setMaxStaleness"
      | "tokenToFeed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircuitBreakerReset"
      | "CircuitBreakerTripped"
      | "DeviationAlert"
      | "KeeperUpdated"
      | "OwnershipTransferred"
      | "PricePushed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DEVIATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STALENESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circuitBreaker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceStore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pushRWAPrice",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFeed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetCircuitBreaker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDeviation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxStaleness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DEVIATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STALENESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "circuitBreaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pushRWAPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetCircuitBreaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDeviation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CircuitBreakerResetEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CircuitBreakerTrippedEvent {
  export type InputTuple = [token: AddressLike, reason: string];
  export type OutputTuple = [token: string, reason: string];
  export interface OutputObject {
    token: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviationAlertEvent {
  export type InputTuple = [
    token: AddressLike,
    oldPrice: BigNumberish,
    newPrice: BigNumberish,
    deviationBps: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    oldPrice: bigint,
    newPrice: bigint,
    deviationBps: bigint
  ];
  export interface OutputObject {
    token: string;
    oldPrice: bigint;
    newPrice: bigint;
    deviationBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeeperUpdatedEvent {
  export type InputTuple = [oldKeeper: AddressLike, newKeeper: AddressLike];
  export type OutputTuple = [oldKeeper: string, newKeeper: string];
  export interface OutputObject {
    oldKeeper: string;
    newKeeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PricePushedEvent {
  export type InputTuple = [
    token: AddressLike,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [token: string, price: bigint, timestamp: bigint];
  export interface OutputObject {
    token: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PriceOracle;
  waitForDeployment(): Promise<this>;

  interface: PriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DEVIATION: TypedContractMethod<[], [bigint], "view">;

  MAX_STALENESS: TypedContractMethod<[], [bigint], "view">;

  circuitBreaker: TypedContractMethod<[], [boolean], "view">;

  getPrice: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { price: bigint; timestamp: bigint }],
    "view"
  >;

  keeper: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceStore: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        timestamp: bigint;
        roundId: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  pushRWAPrice: TypedContractMethod<
    [token: AddressLike, price: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerFeed: TypedContractMethod<
    [token: AddressLike, feed: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetCircuitBreaker: TypedContractMethod<[], [void], "nonpayable">;

  setKeeper: TypedContractMethod<[_keeper: AddressLike], [void], "nonpayable">;

  setMaxDeviation: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxStaleness: TypedContractMethod<
    [seconds_: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenToFeed: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DEVIATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STALENESS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "circuitBreaker"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { price: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "keeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceStore"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        timestamp: bigint;
        roundId: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pushRWAPrice"
  ): TypedContractMethod<
    [token: AddressLike, price: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerFeed"
  ): TypedContractMethod<
    [token: AddressLike, feed: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetCircuitBreaker"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKeeper"
  ): TypedContractMethod<[_keeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxDeviation"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxStaleness"
  ): TypedContractMethod<[seconds_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenToFeed"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CircuitBreakerReset"
  ): TypedContractEvent<
    CircuitBreakerResetEvent.InputTuple,
    CircuitBreakerResetEvent.OutputTuple,
    CircuitBreakerResetEvent.OutputObject
  >;
  getEvent(
    key: "CircuitBreakerTripped"
  ): TypedContractEvent<
    CircuitBreakerTrippedEvent.InputTuple,
    CircuitBreakerTrippedEvent.OutputTuple,
    CircuitBreakerTrippedEvent.OutputObject
  >;
  getEvent(
    key: "DeviationAlert"
  ): TypedContractEvent<
    DeviationAlertEvent.InputTuple,
    DeviationAlertEvent.OutputTuple,
    DeviationAlertEvent.OutputObject
  >;
  getEvent(
    key: "KeeperUpdated"
  ): TypedContractEvent<
    KeeperUpdatedEvent.InputTuple,
    KeeperUpdatedEvent.OutputTuple,
    KeeperUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PricePushed"
  ): TypedContractEvent<
    PricePushedEvent.InputTuple,
    PricePushedEvent.OutputTuple,
    PricePushedEvent.OutputObject
  >;

  filters: {
    "CircuitBreakerReset(address)": TypedContractEvent<
      CircuitBreakerResetEvent.InputTuple,
      CircuitBreakerResetEvent.OutputTuple,
      CircuitBreakerResetEvent.OutputObject
    >;
    CircuitBreakerReset: TypedContractEvent<
      CircuitBreakerResetEvent.InputTuple,
      CircuitBreakerResetEvent.OutputTuple,
      CircuitBreakerResetEvent.OutputObject
    >;

    "CircuitBreakerTripped(address,string)": TypedContractEvent<
      CircuitBreakerTrippedEvent.InputTuple,
      CircuitBreakerTrippedEvent.OutputTuple,
      CircuitBreakerTrippedEvent.OutputObject
    >;
    CircuitBreakerTripped: TypedContractEvent<
      CircuitBreakerTrippedEvent.InputTuple,
      CircuitBreakerTrippedEvent.OutputTuple,
      CircuitBreakerTrippedEvent.OutputObject
    >;

    "DeviationAlert(address,int256,int256,uint256)": TypedContractEvent<
      DeviationAlertEvent.InputTuple,
      DeviationAlertEvent.OutputTuple,
      DeviationAlertEvent.OutputObject
    >;
    DeviationAlert: TypedContractEvent<
      DeviationAlertEvent.InputTuple,
      DeviationAlertEvent.OutputTuple,
      DeviationAlertEvent.OutputObject
    >;

    "KeeperUpdated(address,address)": TypedContractEvent<
      KeeperUpdatedEvent.InputTuple,
      KeeperUpdatedEvent.OutputTuple,
      KeeperUpdatedEvent.OutputObject
    >;
    KeeperUpdated: TypedContractEvent<
      KeeperUpdatedEvent.InputTuple,
      KeeperUpdatedEvent.OutputTuple,
      KeeperUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PricePushed(address,int256,uint256)": TypedContractEvent<
      PricePushedEvent.InputTuple,
      PricePushedEvent.OutputTuple,
      PricePushedEvent.OutputObject
    >;
    PricePushed: TypedContractEvent<
      PricePushedEvent.InputTuple,
      PricePushedEvent.OutputTuple,
      PricePushedEvent.OutputObject
    >;
  };
}
