/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RWAPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_LP_LEVEL"
      | "MIN_SWAP_LEVEL"
      | "addLiquidity"
      | "claimYield"
      | "feeRecipient"
      | "gatewayKeeper"
      | "isLP"
      | "kycRegistry"
      | "lpList"
      | "lpShares"
      | "mintFromGateway"
      | "owner"
      | "pause"
      | "priceOracle"
      | "removeLiquidity"
      | "renounceOwnership"
      | "rewards"
      | "setGatewayKeeper"
      | "setTradeGuard"
      | "state"
      | "swapRWAForStable"
      | "swapStableForRWA"
      | "totalShares"
      | "tradeGuard"
      | "transferOwnership"
      | "unpause"
      | "userYieldPerSharePaid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "LiquidityAddedFromGateway"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
      | "SpreadUpdated"
      | "Swap"
      | "YieldClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_LP_LEVEL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SWAP_LEVEL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gatewayKeeper",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isLP", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "kycRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintFromGateway",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGatewayKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradeGuard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapRWAForStable",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapStableForRWA",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradeGuard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userYieldPerSharePaid",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_LP_LEVEL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SWAP_LEVEL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gatewayKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kycRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintFromGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGatewayKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradeGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapRWAForStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapStableForRWA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tradeGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userYieldPerSharePaid",
    data: BytesLike
  ): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    lp: AddressLike,
    rwaAmount: BigNumberish,
    stableAmount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    lp: string,
    rwaAmount: bigint,
    stableAmount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    lp: string;
    rwaAmount: bigint;
    stableAmount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedFromGatewayEvent {
  export type InputTuple = [
    lp: AddressLike,
    stableAmount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [lp: string, stableAmount: bigint, shares: bigint];
  export interface OutputObject {
    lp: string;
    stableAmount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    lp: AddressLike,
    rwaAmount: BigNumberish,
    stableAmount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    lp: string,
    rwaAmount: bigint,
    stableAmount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    lp: string;
    rwaAmount: bigint;
    stableAmount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpreadUpdatedEvent {
  export type InputTuple = [oldBps: BigNumberish, newBps: BigNumberish];
  export type OutputTuple = [oldBps: bigint, newBps: bigint];
  export interface OutputObject {
    oldBps: bigint;
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    executionPrice: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    executionPrice: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    executionPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [lp: AddressLike, amount: BigNumberish];
  export type OutputTuple = [lp: string, amount: bigint];
  export interface OutputObject {
    lp: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWAPool extends BaseContract {
  connect(runner?: ContractRunner | null): RWAPool;
  waitForDeployment(): Promise<this>;

  interface: RWAPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_LP_LEVEL: TypedContractMethod<[], [bigint], "view">;

  MIN_SWAP_LEVEL: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [rwaAmount: BigNumberish, stableAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimYield: TypedContractMethod<[], [bigint], "nonpayable">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  gatewayKeeper: TypedContractMethod<[], [string], "view">;

  isLP: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  kycRegistry: TypedContractMethod<[], [string], "view">;

  lpList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  lpShares: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mintFromGateway: TypedContractMethod<
    [lp: AddressLike, stableAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setGatewayKeeper: TypedContractMethod<
    [_gatewayKeeper: AddressLike],
    [void],
    "nonpayable"
  >;

  setTradeGuard: TypedContractMethod<
    [_tradeGuard: AddressLike],
    [void],
    "nonpayable"
  >;

  state: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        rwaToken: string;
        stableToken: string;
        rwaReserve: bigint;
        stableReserve: bigint;
        spreadBps: bigint;
        feeBps: bigint;
        accumulatedFees: bigint;
        accYieldPerShare: bigint;
        paused: boolean;
      }
    ],
    "view"
  >;

  swapRWAForStable: TypedContractMethod<
    [rwaAmountIn: BigNumberish, minStableOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapStableForRWA: TypedContractMethod<
    [stableAmountIn: BigNumberish, minRWAOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  tradeGuard: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userYieldPerSharePaid: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_LP_LEVEL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SWAP_LEVEL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [rwaAmount: BigNumberish, stableAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gatewayKeeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isLP"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lpList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "lpShares"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintFromGateway"
  ): TypedContractMethod<
    [lp: AddressLike, stableAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGatewayKeeper"
  ): TypedContractMethod<[_gatewayKeeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTradeGuard"
  ): TypedContractMethod<[_tradeGuard: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        rwaToken: string;
        stableToken: string;
        rwaReserve: bigint;
        stableReserve: bigint;
        spreadBps: bigint;
        feeBps: bigint;
        accumulatedFees: bigint;
        accYieldPerShare: bigint;
        paused: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "swapRWAForStable"
  ): TypedContractMethod<
    [rwaAmountIn: BigNumberish, minStableOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapStableForRWA"
  ): TypedContractMethod<
    [stableAmountIn: BigNumberish, minRWAOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tradeGuard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userYieldPerSharePaid"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAddedFromGateway"
  ): TypedContractEvent<
    LiquidityAddedFromGatewayEvent.InputTuple,
    LiquidityAddedFromGatewayEvent.OutputTuple,
    LiquidityAddedFromGatewayEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SpreadUpdated"
  ): TypedContractEvent<
    SpreadUpdatedEvent.InputTuple,
    SpreadUpdatedEvent.OutputTuple,
    SpreadUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityAddedFromGateway(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedFromGatewayEvent.InputTuple,
      LiquidityAddedFromGatewayEvent.OutputTuple,
      LiquidityAddedFromGatewayEvent.OutputObject
    >;
    LiquidityAddedFromGateway: TypedContractEvent<
      LiquidityAddedFromGatewayEvent.InputTuple,
      LiquidityAddedFromGatewayEvent.OutputTuple,
      LiquidityAddedFromGatewayEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SpreadUpdated(uint256,uint256)": TypedContractEvent<
      SpreadUpdatedEvent.InputTuple,
      SpreadUpdatedEvent.OutputTuple,
      SpreadUpdatedEvent.OutputObject
    >;
    SpreadUpdated: TypedContractEvent<
      SpreadUpdatedEvent.InputTuple,
      SpreadUpdatedEvent.OutputTuple,
      SpreadUpdatedEvent.OutputObject
    >;

    "Swap(address,address,address,uint256,uint256,int256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "YieldClaimed(address,uint256)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
  };
}
