/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IKycSBTInterface extends Interface {
  getFunction(nameOrSignature: "getKycInfo" | "isHuman"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getKycInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isHuman",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getKycInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isHuman", data: BytesLike): Result;
}

export interface IKycSBT extends BaseContract {
  connect(runner?: ContractRunner | null): IKycSBT;
  waitForDeployment(): Promise<this>;

  interface: IKycSBTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getKycInfo: TypedContractMethod<
    [account: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        ensName: string;
        level: bigint;
        status: bigint;
        createTime: bigint;
      }
    ],
    "view"
  >;

  isHuman: TypedContractMethod<
    [account: AddressLike],
    [[boolean, bigint]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getKycInfo"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        ensName: string;
        level: bigint;
        status: bigint;
        createTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isHuman"
  ): TypedContractMethod<[account: AddressLike], [[boolean, bigint]], "view">;

  filters: {};
}
