/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRWAPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "distributeYield"
      | "removeLiquidity"
      | "setTradeGuard"
      | "swapRWAForStable"
      | "swapStableForRWA"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradeGuard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRWAForStable",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapStableForRWA",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradeGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRWAForStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapStableForRWA",
    data: BytesLike
  ): Result;
}

export interface IRWAPool extends BaseContract {
  connect(runner?: ContractRunner | null): IRWAPool;
  waitForDeployment(): Promise<this>;

  interface: IRWAPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [rwaAmount: BigNumberish, stableAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeYield: TypedContractMethod<[], [void], "nonpayable">;

  removeLiquidity: TypedContractMethod<
    [shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTradeGuard: TypedContractMethod<
    [tradeGuard: AddressLike],
    [void],
    "nonpayable"
  >;

  swapRWAForStable: TypedContractMethod<
    [rwaAmountIn: BigNumberish, minStableOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapStableForRWA: TypedContractMethod<
    [stableAmountIn: BigNumberish, minRWAOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [rwaAmount: BigNumberish, stableAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTradeGuard"
  ): TypedContractMethod<[tradeGuard: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapRWAForStable"
  ): TypedContractMethod<
    [rwaAmountIn: BigNumberish, minStableOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapStableForRWA"
  ): TypedContractMethod<
    [stableAmountIn: BigNumberish, minRWAOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
