/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRWAPoolState,
  IRWAPoolStateInterface,
} from "../../../contracts/TradeGuard.sol/IRWAPoolState";

const _abi = [
  {
    inputs: [],
    name: "state",
    outputs: [
      {
        internalType: "address",
        name: "rwaToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "stableToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rwaReserve",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stableReserve",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "spreadBps",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeBps",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "accumulatedFees",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "paused",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRWAPoolState__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAPoolStateInterface {
    return new Interface(_abi) as IRWAPoolStateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRWAPoolState {
    return new Contract(address, _abi, runner) as unknown as IRWAPoolState;
  }
}
