/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRWAPoolStateInterface extends Interface {
  getFunction(nameOrSignature: "state"): FunctionFragment;

  encodeFunctionData(functionFragment: "state", values?: undefined): string;

  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
}

export interface IRWAPoolState extends BaseContract {
  connect(runner?: ContractRunner | null): IRWAPoolState;
  waitForDeployment(): Promise<this>;

  interface: IRWAPoolStateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  state: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        rwaToken: string;
        stableToken: string;
        rwaReserve: bigint;
        stableReserve: bigint;
        spreadBps: bigint;
        feeBps: bigint;
        accumulatedFees: bigint;
        paused: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        rwaToken: string;
        stableToken: string;
        rwaReserve: bigint;
        stableReserve: bigint;
        spreadBps: bigint;
        feeBps: bigint;
        accumulatedFees: bigint;
        paused: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
