/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TradeGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DELAY_BLOCKS"
      | "LARGE_SWAP_THRESHOLD"
      | "MAX_DELAY_BLOCKS"
      | "cancelSwap"
      | "commitSwap"
      | "commitments"
      | "executeSwap"
      | "hashSwapParams"
      | "owner"
      | "pool"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SwapCancelled"
      | "SwapCommitted"
      | "SwapExecuted"
      | "ThresholdUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DELAY_BLOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LARGE_SWAP_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DELAY_BLOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSwap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSwap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSwap",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashSwapParams",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DELAY_BLOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LARGE_SWAP_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DELAY_BLOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commitSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashSwapParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapCancelledEvent {
  export type InputTuple = [commitId: BytesLike, user: AddressLike];
  export type OutputTuple = [commitId: string, user: string];
  export interface OutputObject {
    commitId: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapCommittedEvent {
  export type InputTuple = [
    commitId: BytesLike,
    user: AddressLike,
    commitBlock: BigNumberish
  ];
  export type OutputTuple = [
    commitId: string,
    user: string,
    commitBlock: bigint
  ];
  export interface OutputObject {
    commitId: string;
    user: string;
    commitBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    commitId: BytesLike,
    user: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    commitId: string,
    user: string,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    commitId: string;
    user: string;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TradeGuard extends BaseContract {
  connect(runner?: ContractRunner | null): TradeGuard;
  waitForDeployment(): Promise<this>;

  interface: TradeGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DELAY_BLOCKS: TypedContractMethod<[], [bigint], "view">;

  LARGE_SWAP_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_DELAY_BLOCKS: TypedContractMethod<[], [bigint], "view">;

  cancelSwap: TypedContractMethod<[commitId: BytesLike], [void], "nonpayable">;

  commitSwap: TypedContractMethod<
    [paramHash: BytesLike],
    [string],
    "nonpayable"
  >;

  commitments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        paramHash: string;
        user: string;
        commitBlock: bigint;
        expireBlock: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  executeSwap: TypedContractMethod<
    [
      commitId: BytesLike,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minOut: BigNumberish,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  hashSwapParams: TypedContractMethod<
    [
      user: AddressLike,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minOut: BigNumberish,
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DELAY_BLOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LARGE_SWAP_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DELAY_BLOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelSwap"
  ): TypedContractMethod<[commitId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitSwap"
  ): TypedContractMethod<[paramHash: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        paramHash: string;
        user: string;
        commitBlock: bigint;
        expireBlock: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeSwap"
  ): TypedContractMethod<
    [
      commitId: BytesLike,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minOut: BigNumberish,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hashSwapParams"
  ): TypedContractMethod<
    [
      user: AddressLike,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minOut: BigNumberish,
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SwapCancelled"
  ): TypedContractEvent<
    SwapCancelledEvent.InputTuple,
    SwapCancelledEvent.OutputTuple,
    SwapCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SwapCommitted"
  ): TypedContractEvent<
    SwapCommittedEvent.InputTuple,
    SwapCommittedEvent.OutputTuple,
    SwapCommittedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SwapCancelled(bytes32,address)": TypedContractEvent<
      SwapCancelledEvent.InputTuple,
      SwapCancelledEvent.OutputTuple,
      SwapCancelledEvent.OutputObject
    >;
    SwapCancelled: TypedContractEvent<
      SwapCancelledEvent.InputTuple,
      SwapCancelledEvent.OutputTuple,
      SwapCancelledEvent.OutputObject
    >;

    "SwapCommitted(bytes32,address,uint256)": TypedContractEvent<
      SwapCommittedEvent.InputTuple,
      SwapCommittedEvent.OutputTuple,
      SwapCommittedEvent.OutputObject
    >;
    SwapCommitted: TypedContractEvent<
      SwapCommittedEvent.InputTuple,
      SwapCommittedEvent.OutputTuple,
      SwapCommittedEvent.OutputObject
    >;

    "SwapExecuted(bytes32,address,uint256,uint256)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
  };
}
