/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tradeGuardSol from "./TradeGuard.sol";
export * as interfaces from "./interfaces";
export { KYCRegistry__factory } from "./KYCRegistry__factory";
export { MockKycSBT__factory } from "./MockKycSBT__factory";
export { PriceOracle__factory } from "./PriceOracle__factory";
export { RWAPool__factory } from "./RWAPool__factory";
export { RWAToken__factory } from "./RWAToken__factory";
