/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHSPPayment,
  IHSPPaymentInterface,
} from "../../../contracts/interfaces/IHSPPayment";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "recipients",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    name: "batchStream",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHSPPayment__factory {
  static readonly abi = _abi;
  static createInterface(): IHSPPaymentInterface {
    return new Interface(_abi) as IHSPPaymentInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IHSPPayment {
    return new Contract(address, _abi, runner) as unknown as IHSPPayment;
  }
}
