/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKYCRegistry,
  IKYCRegistryInterface,
} from "../../../contracts/interfaces/IKYCRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getLevel",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isRevoked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "minLevel",
        type: "uint8",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKYCRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IKYCRegistryInterface {
    return new Interface(_abi) as IKYCRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKYCRegistry {
    return new Contract(address, _abi, runner) as unknown as IKYCRegistry;
  }
}
