/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKycSBT,
  IKycSBTInterface,
} from "../../../contracts/interfaces/IKycSBT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getKycInfo",
    outputs: [
      {
        internalType: "string",
        name: "ensName",
        type: "string",
      },
      {
        internalType: "enum IKycSBT.KycLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "enum IKycSBT.KycStatus",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "createTime",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKycSBT__factory {
  static readonly abi = _abi;
  static createInterface(): IKycSBTInterface {
    return new Interface(_abi) as IKycSBTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IKycSBT {
    return new Contract(address, _abi, runner) as unknown as IKycSBT;
  }
}
