/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRWAPool,
  IRWAPoolInterface,
} from "../../../contracts/interfaces/IRWAPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "rwaAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stableAmount",
        type: "uint256",
      },
    ],
    name: "addLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "distributeYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "removeLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tradeGuard",
        type: "address",
      },
    ],
    name: "setTradeGuard",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "rwaAmountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minStableOut",
        type: "uint256",
      },
    ],
    name: "swapRWAForStable",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stableAmountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minRWAOut",
        type: "uint256",
      },
    ],
    name: "swapStableForRWA",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRWAPool__factory {
  static readonly abi = _abi;
  static createInterface(): IRWAPoolInterface {
    return new Interface(_abi) as IRWAPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRWAPool {
    return new Contract(address, _abi, runner) as unknown as IRWAPool;
  }
}
